# Generated by Django 5.2.5 on 2026-07-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_response_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
