# Generated by Django 5.2.6 on 2025-09-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Com2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("upload", models.FileField(upload_to="uploads_com2/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
